# Generated by Django 6.0.6 on 2026-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='photes/product_images'),
            preserve_default=False,
        ),
    ]
